// Code generated by go-swagger; DO NOT EDIT.

package promocode

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cli/models"
)

// ActivateReader is a Reader for the Activate structure.
type ActivateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ActivateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewActivateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewActivateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewActivateForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewActivateOK creates a ActivateOK with default headers values
func NewActivateOK() *ActivateOK {
	return &ActivateOK{}
}

/*ActivateOK handles this case with default header values.

Success
*/
type ActivateOK struct {
	Payload *models.PromocodeActivationResultDto
}

func (o *ActivateOK) Error() string {
	return fmt.Sprintf("[POST /api/promocode/activate/{code}][%d] activateOK  %+v", 200, o.Payload)
}

func (o *ActivateOK) GetPayload() *models.PromocodeActivationResultDto {
	return o.Payload
}

func (o *ActivateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PromocodeActivationResultDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewActivateUnauthorized creates a ActivateUnauthorized with default headers values
func NewActivateUnauthorized() *ActivateUnauthorized {
	return &ActivateUnauthorized{}
}

/*ActivateUnauthorized handles this case with default header values.

Unauthorized
*/
type ActivateUnauthorized struct {
}

func (o *ActivateUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/promocode/activate/{code}][%d] activateUnauthorized ", 401)
}

func (o *ActivateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewActivateForbidden creates a ActivateForbidden with default headers values
func NewActivateForbidden() *ActivateForbidden {
	return &ActivateForbidden{}
}

/*ActivateForbidden handles this case with default header values.

Forbidden
*/
type ActivateForbidden struct {
}

func (o *ActivateForbidden) Error() string {
	return fmt.Sprintf("[POST /api/promocode/activate/{code}][%d] activateForbidden ", 403)
}

func (o *ActivateForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
