// Code generated by go-swagger; DO NOT EDIT.

package promocode

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new promocode API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for promocode API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	Activate(params *ActivateParams, authInfo runtime.ClientAuthInfoWriter) (*ActivateOK, error)

	SetActivity(params *SetActivityParams, authInfo runtime.ClientAuthInfoWriter) (*SetActivityOK, error)

	SetAmount(params *SetAmountParams, authInfo runtime.ClientAuthInfoWriter) (*SetAmountOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  Activate activate API
*/
func (a *Client) Activate(params *ActivateParams, authInfo runtime.ClientAuthInfoWriter) (*ActivateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewActivateParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Activate",
		Method:             "POST",
		PathPattern:        "/api/promocode/activate/{code}",
		ProducesMediaTypes: []string{"application/json", "text/json", "text/plain"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ActivateReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ActivateOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Activate: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  SetActivity set activity API
*/
func (a *Client) SetActivity(params *SetActivityParams, authInfo runtime.ClientAuthInfoWriter) (*SetActivityOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSetActivityParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "SetActivity",
		Method:             "PUT",
		PathPattern:        "/api/promocode/set-activity/{code}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &SetActivityReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*SetActivityOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for SetActivity: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  SetAmount set amount API
*/
func (a *Client) SetAmount(params *SetAmountParams, authInfo runtime.ClientAuthInfoWriter) (*SetAmountOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSetAmountParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "SetAmount",
		Method:             "PUT",
		PathPattern:        "/api/promocode/set-amount/{code}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &SetAmountReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*SetAmountOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for SetAmount: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
