// Code generated by go-swagger; DO NOT EDIT.

package promocode

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SetActivityReader is a Reader for the SetActivity structure.
type SetActivityReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetActivityReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSetActivityOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewSetActivityUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewSetActivityForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSetActivityOK creates a SetActivityOK with default headers values
func NewSetActivityOK() *SetActivityOK {
	return &SetActivityOK{}
}

/*SetActivityOK handles this case with default header values.

Success
*/
type SetActivityOK struct {
}

func (o *SetActivityOK) Error() string {
	return fmt.Sprintf("[PUT /api/promocode/set-activity/{code}][%d] setActivityOK ", 200)
}

func (o *SetActivityOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSetActivityUnauthorized creates a SetActivityUnauthorized with default headers values
func NewSetActivityUnauthorized() *SetActivityUnauthorized {
	return &SetActivityUnauthorized{}
}

/*SetActivityUnauthorized handles this case with default header values.

Unauthorized
*/
type SetActivityUnauthorized struct {
}

func (o *SetActivityUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /api/promocode/set-activity/{code}][%d] setActivityUnauthorized ", 401)
}

func (o *SetActivityUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSetActivityForbidden creates a SetActivityForbidden with default headers values
func NewSetActivityForbidden() *SetActivityForbidden {
	return &SetActivityForbidden{}
}

/*SetActivityForbidden handles this case with default header values.

Forbidden
*/
type SetActivityForbidden struct {
}

func (o *SetActivityForbidden) Error() string {
	return fmt.Sprintf("[PUT /api/promocode/set-activity/{code}][%d] setActivityForbidden ", 403)
}

func (o *SetActivityForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
