// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"cli/models"
)

// NewPutAPIUserParams creates a new PutAPIUserParams object
// with the default values initialized.
func NewPutAPIUserParams() *PutAPIUserParams {
	var ()
	return &PutAPIUserParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIUserParamsWithTimeout creates a new PutAPIUserParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutAPIUserParamsWithTimeout(timeout time.Duration) *PutAPIUserParams {
	var ()
	return &PutAPIUserParams{

		timeout: timeout,
	}
}

// NewPutAPIUserParamsWithContext creates a new PutAPIUserParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutAPIUserParamsWithContext(ctx context.Context) *PutAPIUserParams {
	var ()
	return &PutAPIUserParams{

		Context: ctx,
	}
}

// NewPutAPIUserParamsWithHTTPClient creates a new PutAPIUserParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutAPIUserParamsWithHTTPClient(client *http.Client) *PutAPIUserParams {
	var ()
	return &PutAPIUserParams{
		HTTPClient: client,
	}
}

/*PutAPIUserParams contains all the parameters to send to the API endpoint
for the put API user operation typically these are written to a http.Request
*/
type PutAPIUserParams struct {

	/*UserSummary
	  Новые данные о пользователе

	*/
	UserSummary *models.UserSummaryDto

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put API user params
func (o *PutAPIUserParams) WithTimeout(timeout time.Duration) *PutAPIUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put API user params
func (o *PutAPIUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put API user params
func (o *PutAPIUserParams) WithContext(ctx context.Context) *PutAPIUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put API user params
func (o *PutAPIUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put API user params
func (o *PutAPIUserParams) WithHTTPClient(client *http.Client) *PutAPIUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put API user params
func (o *PutAPIUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserSummary adds the userSummary to the put API user params
func (o *PutAPIUserParams) WithUserSummary(userSummary *models.UserSummaryDto) *PutAPIUserParams {
	o.SetUserSummary(userSummary)
	return o
}

// SetUserSummary adds the userSummary to the put API user params
func (o *PutAPIUserParams) SetUserSummary(userSummary *models.UserSummaryDto) {
	o.UserSummary = userSummary
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.UserSummary != nil {
		if err := r.SetBodyParam(o.UserSummary); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
