// Code generated by go-swagger; DO NOT EDIT.

package domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewAddTLSKeyParams creates a new AddTLSKeyParams object
// with the default values initialized.
func NewAddTLSKeyParams() *AddTLSKeyParams {
	var ()
	return &AddTLSKeyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddTLSKeyParamsWithTimeout creates a new AddTLSKeyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddTLSKeyParamsWithTimeout(timeout time.Duration) *AddTLSKeyParams {
	var ()
	return &AddTLSKeyParams{

		timeout: timeout,
	}
}

// NewAddTLSKeyParamsWithContext creates a new AddTLSKeyParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddTLSKeyParamsWithContext(ctx context.Context) *AddTLSKeyParams {
	var ()
	return &AddTLSKeyParams{

		Context: ctx,
	}
}

// NewAddTLSKeyParamsWithHTTPClient creates a new AddTLSKeyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddTLSKeyParamsWithHTTPClient(client *http.Client) *AddTLSKeyParams {
	var ()
	return &AddTLSKeyParams{
		HTTPClient: client,
	}
}

/*AddTLSKeyParams contains all the parameters to send to the API endpoint
for the add Tls key operation typically these are written to a http.Request
*/
type AddTLSKeyParams struct {

	/*File*/
	File runtime.NamedReadCloser
	/*ID*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add Tls key params
func (o *AddTLSKeyParams) WithTimeout(timeout time.Duration) *AddTLSKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add Tls key params
func (o *AddTLSKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add Tls key params
func (o *AddTLSKeyParams) WithContext(ctx context.Context) *AddTLSKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add Tls key params
func (o *AddTLSKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add Tls key params
func (o *AddTLSKeyParams) WithHTTPClient(client *http.Client) *AddTLSKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add Tls key params
func (o *AddTLSKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFile adds the file to the add Tls key params
func (o *AddTLSKeyParams) WithFile(file runtime.NamedReadCloser) *AddTLSKeyParams {
	o.SetFile(file)
	return o
}

// SetFile adds the file to the add Tls key params
func (o *AddTLSKeyParams) SetFile(file runtime.NamedReadCloser) {
	o.File = file
}

// WithID adds the id to the add Tls key params
func (o *AddTLSKeyParams) WithID(id int32) *AddTLSKeyParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the add Tls key params
func (o *AddTLSKeyParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *AddTLSKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.File != nil {

		if o.File != nil {

			// form file param file
			if err := r.SetFileParam("file", o.File); err != nil {
				return err
			}

		}

	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
