// Code generated by go-swagger; DO NOT EDIT.

package domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDownloadTLSPrivateKeyParams creates a new DownloadTLSPrivateKeyParams object
// with the default values initialized.
func NewDownloadTLSPrivateKeyParams() *DownloadTLSPrivateKeyParams {
	var ()
	return &DownloadTLSPrivateKeyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDownloadTLSPrivateKeyParamsWithTimeout creates a new DownloadTLSPrivateKeyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDownloadTLSPrivateKeyParamsWithTimeout(timeout time.Duration) *DownloadTLSPrivateKeyParams {
	var ()
	return &DownloadTLSPrivateKeyParams{

		timeout: timeout,
	}
}

// NewDownloadTLSPrivateKeyParamsWithContext creates a new DownloadTLSPrivateKeyParams object
// with the default values initialized, and the ability to set a context for a request
func NewDownloadTLSPrivateKeyParamsWithContext(ctx context.Context) *DownloadTLSPrivateKeyParams {
	var ()
	return &DownloadTLSPrivateKeyParams{

		Context: ctx,
	}
}

// NewDownloadTLSPrivateKeyParamsWithHTTPClient creates a new DownloadTLSPrivateKeyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDownloadTLSPrivateKeyParamsWithHTTPClient(client *http.Client) *DownloadTLSPrivateKeyParams {
	var ()
	return &DownloadTLSPrivateKeyParams{
		HTTPClient: client,
	}
}

/*DownloadTLSPrivateKeyParams contains all the parameters to send to the API endpoint
for the download Tls private key operation typically these are written to a http.Request
*/
type DownloadTLSPrivateKeyParams struct {

	/*ID*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the download Tls private key params
func (o *DownloadTLSPrivateKeyParams) WithTimeout(timeout time.Duration) *DownloadTLSPrivateKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the download Tls private key params
func (o *DownloadTLSPrivateKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the download Tls private key params
func (o *DownloadTLSPrivateKeyParams) WithContext(ctx context.Context) *DownloadTLSPrivateKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the download Tls private key params
func (o *DownloadTLSPrivateKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the download Tls private key params
func (o *DownloadTLSPrivateKeyParams) WithHTTPClient(client *http.Client) *DownloadTLSPrivateKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the download Tls private key params
func (o *DownloadTLSPrivateKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the download Tls private key params
func (o *DownloadTLSPrivateKeyParams) WithID(id int32) *DownloadTLSPrivateKeyParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the download Tls private key params
func (o *DownloadTLSPrivateKeyParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DownloadTLSPrivateKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
