// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetOccupiedResourcesParams creates a new GetOccupiedResourcesParams object
// with the default values initialized.
func NewGetOccupiedResourcesParams() *GetOccupiedResourcesParams {
	var ()
	return &GetOccupiedResourcesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOccupiedResourcesParamsWithTimeout creates a new GetOccupiedResourcesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOccupiedResourcesParamsWithTimeout(timeout time.Duration) *GetOccupiedResourcesParams {
	var ()
	return &GetOccupiedResourcesParams{

		timeout: timeout,
	}
}

// NewGetOccupiedResourcesParamsWithContext creates a new GetOccupiedResourcesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOccupiedResourcesParamsWithContext(ctx context.Context) *GetOccupiedResourcesParams {
	var ()
	return &GetOccupiedResourcesParams{

		Context: ctx,
	}
}

// NewGetOccupiedResourcesParamsWithHTTPClient creates a new GetOccupiedResourcesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOccupiedResourcesParamsWithHTTPClient(client *http.Client) *GetOccupiedResourcesParams {
	var ()
	return &GetOccupiedResourcesParams{
		HTTPClient: client,
	}
}

/*GetOccupiedResourcesParams contains all the parameters to send to the API endpoint
for the get occupied resources operation typically these are written to a http.Request
*/
type GetOccupiedResourcesParams struct {

	/*User*/
	User string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get occupied resources params
func (o *GetOccupiedResourcesParams) WithTimeout(timeout time.Duration) *GetOccupiedResourcesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get occupied resources params
func (o *GetOccupiedResourcesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get occupied resources params
func (o *GetOccupiedResourcesParams) WithContext(ctx context.Context) *GetOccupiedResourcesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get occupied resources params
func (o *GetOccupiedResourcesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get occupied resources params
func (o *GetOccupiedResourcesParams) WithHTTPClient(client *http.Client) *GetOccupiedResourcesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get occupied resources params
func (o *GetOccupiedResourcesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUser adds the user to the get occupied resources params
func (o *GetOccupiedResourcesParams) WithUser(user string) *GetOccupiedResourcesParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the get occupied resources params
func (o *GetOccupiedResourcesParams) SetUser(user string) {
	o.User = user
}

// WriteToRequest writes these params to a swagger request
func (o *GetOccupiedResourcesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param user
	if err := r.SetPathParam("user", o.User); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
