// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAvaiableLimitsParams creates a new GetAvaiableLimitsParams object
// with the default values initialized.
func NewGetAvaiableLimitsParams() *GetAvaiableLimitsParams {
	var ()
	return &GetAvaiableLimitsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAvaiableLimitsParamsWithTimeout creates a new GetAvaiableLimitsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAvaiableLimitsParamsWithTimeout(timeout time.Duration) *GetAvaiableLimitsParams {
	var ()
	return &GetAvaiableLimitsParams{

		timeout: timeout,
	}
}

// NewGetAvaiableLimitsParamsWithContext creates a new GetAvaiableLimitsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAvaiableLimitsParamsWithContext(ctx context.Context) *GetAvaiableLimitsParams {
	var ()
	return &GetAvaiableLimitsParams{

		Context: ctx,
	}
}

// NewGetAvaiableLimitsParamsWithHTTPClient creates a new GetAvaiableLimitsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAvaiableLimitsParamsWithHTTPClient(client *http.Client) *GetAvaiableLimitsParams {
	var ()
	return &GetAvaiableLimitsParams{
		HTTPClient: client,
	}
}

/*GetAvaiableLimitsParams contains all the parameters to send to the API endpoint
for the get avaiable limits operation typically these are written to a http.Request
*/
type GetAvaiableLimitsParams struct {

	/*User*/
	User string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get avaiable limits params
func (o *GetAvaiableLimitsParams) WithTimeout(timeout time.Duration) *GetAvaiableLimitsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get avaiable limits params
func (o *GetAvaiableLimitsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get avaiable limits params
func (o *GetAvaiableLimitsParams) WithContext(ctx context.Context) *GetAvaiableLimitsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get avaiable limits params
func (o *GetAvaiableLimitsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get avaiable limits params
func (o *GetAvaiableLimitsParams) WithHTTPClient(client *http.Client) *GetAvaiableLimitsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get avaiable limits params
func (o *GetAvaiableLimitsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUser adds the user to the get avaiable limits params
func (o *GetAvaiableLimitsParams) WithUser(user string) *GetAvaiableLimitsParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the get avaiable limits params
func (o *GetAvaiableLimitsParams) SetUser(user string) {
	o.User = user
}

// WriteToRequest writes these params to a swagger request
func (o *GetAvaiableLimitsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param user
	if err := r.SetPathParam("user", o.User); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
