// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cli/models"
)

// GetUsedByAppResourcesReader is a Reader for the GetUsedByAppResources structure.
type GetUsedByAppResourcesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUsedByAppResourcesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetUsedByAppResourcesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetUsedByAppResourcesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetUsedByAppResourcesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetUsedByAppResourcesOK creates a GetUsedByAppResourcesOK with default headers values
func NewGetUsedByAppResourcesOK() *GetUsedByAppResourcesOK {
	return &GetUsedByAppResourcesOK{}
}

/*GetUsedByAppResourcesOK handles this case with default header values.

Success
*/
type GetUsedByAppResourcesOK struct {
	Payload *models.UserOccupiedResourcesDto
}

func (o *GetUsedByAppResourcesOK) Error() string {
	return fmt.Sprintf("[GET /api/resources/occupied-resources-app/{user}][%d] getUsedByAppResourcesOK  %+v", 200, o.Payload)
}

func (o *GetUsedByAppResourcesOK) GetPayload() *models.UserOccupiedResourcesDto {
	return o.Payload
}

func (o *GetUsedByAppResourcesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserOccupiedResourcesDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUsedByAppResourcesUnauthorized creates a GetUsedByAppResourcesUnauthorized with default headers values
func NewGetUsedByAppResourcesUnauthorized() *GetUsedByAppResourcesUnauthorized {
	return &GetUsedByAppResourcesUnauthorized{}
}

/*GetUsedByAppResourcesUnauthorized handles this case with default header values.

Unauthorized
*/
type GetUsedByAppResourcesUnauthorized struct {
}

func (o *GetUsedByAppResourcesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/resources/occupied-resources-app/{user}][%d] getUsedByAppResourcesUnauthorized ", 401)
}

func (o *GetUsedByAppResourcesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetUsedByAppResourcesForbidden creates a GetUsedByAppResourcesForbidden with default headers values
func NewGetUsedByAppResourcesForbidden() *GetUsedByAppResourcesForbidden {
	return &GetUsedByAppResourcesForbidden{}
}

/*GetUsedByAppResourcesForbidden handles this case with default header values.

Forbidden
*/
type GetUsedByAppResourcesForbidden struct {
}

func (o *GetUsedByAppResourcesForbidden) Error() string {
	return fmt.Sprintf("[GET /api/resources/occupied-resources-app/{user}][%d] getUsedByAppResourcesForbidden ", 403)
}

func (o *GetUsedByAppResourcesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
