// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cli/models"
)

// GetLimitsReader is a Reader for the GetLimits structure.
type GetLimitsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLimitsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLimitsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetLimitsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetLimitsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLimitsOK creates a GetLimitsOK with default headers values
func NewGetLimitsOK() *GetLimitsOK {
	return &GetLimitsOK{}
}

/*GetLimitsOK handles this case with default header values.

Success
*/
type GetLimitsOK struct {
	Payload *models.UserAvailableLimitsDto
}

func (o *GetLimitsOK) Error() string {
	return fmt.Sprintf("[GET /api/resources/limits/{user}][%d] getLimitsOK  %+v", 200, o.Payload)
}

func (o *GetLimitsOK) GetPayload() *models.UserAvailableLimitsDto {
	return o.Payload
}

func (o *GetLimitsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserAvailableLimitsDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLimitsUnauthorized creates a GetLimitsUnauthorized with default headers values
func NewGetLimitsUnauthorized() *GetLimitsUnauthorized {
	return &GetLimitsUnauthorized{}
}

/*GetLimitsUnauthorized handles this case with default header values.

Unauthorized
*/
type GetLimitsUnauthorized struct {
}

func (o *GetLimitsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/resources/limits/{user}][%d] getLimitsUnauthorized ", 401)
}

func (o *GetLimitsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetLimitsForbidden creates a GetLimitsForbidden with default headers values
func NewGetLimitsForbidden() *GetLimitsForbidden {
	return &GetLimitsForbidden{}
}

/*GetLimitsForbidden handles this case with default header values.

Forbidden
*/
type GetLimitsForbidden struct {
}

func (o *GetLimitsForbidden) Error() string {
	return fmt.Sprintf("[GET /api/resources/limits/{user}][%d] getLimitsForbidden ", 403)
}

func (o *GetLimitsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
