// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetUsedByAppResourcesParams creates a new GetUsedByAppResourcesParams object
// with the default values initialized.
func NewGetUsedByAppResourcesParams() *GetUsedByAppResourcesParams {
	var ()
	return &GetUsedByAppResourcesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetUsedByAppResourcesParamsWithTimeout creates a new GetUsedByAppResourcesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetUsedByAppResourcesParamsWithTimeout(timeout time.Duration) *GetUsedByAppResourcesParams {
	var ()
	return &GetUsedByAppResourcesParams{

		timeout: timeout,
	}
}

// NewGetUsedByAppResourcesParamsWithContext creates a new GetUsedByAppResourcesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetUsedByAppResourcesParamsWithContext(ctx context.Context) *GetUsedByAppResourcesParams {
	var ()
	return &GetUsedByAppResourcesParams{

		Context: ctx,
	}
}

// NewGetUsedByAppResourcesParamsWithHTTPClient creates a new GetUsedByAppResourcesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetUsedByAppResourcesParamsWithHTTPClient(client *http.Client) *GetUsedByAppResourcesParams {
	var ()
	return &GetUsedByAppResourcesParams{
		HTTPClient: client,
	}
}

/*GetUsedByAppResourcesParams contains all the parameters to send to the API endpoint
for the get used by app resources operation typically these are written to a http.Request
*/
type GetUsedByAppResourcesParams struct {

	/*AppID*/
	AppID *int32
	/*User*/
	User string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get used by app resources params
func (o *GetUsedByAppResourcesParams) WithTimeout(timeout time.Duration) *GetUsedByAppResourcesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get used by app resources params
func (o *GetUsedByAppResourcesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get used by app resources params
func (o *GetUsedByAppResourcesParams) WithContext(ctx context.Context) *GetUsedByAppResourcesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get used by app resources params
func (o *GetUsedByAppResourcesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get used by app resources params
func (o *GetUsedByAppResourcesParams) WithHTTPClient(client *http.Client) *GetUsedByAppResourcesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get used by app resources params
func (o *GetUsedByAppResourcesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the get used by app resources params
func (o *GetUsedByAppResourcesParams) WithAppID(appID *int32) *GetUsedByAppResourcesParams {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the get used by app resources params
func (o *GetUsedByAppResourcesParams) SetAppID(appID *int32) {
	o.AppID = appID
}

// WithUser adds the user to the get used by app resources params
func (o *GetUsedByAppResourcesParams) WithUser(user string) *GetUsedByAppResourcesParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the get used by app resources params
func (o *GetUsedByAppResourcesParams) SetUser(user string) {
	o.User = user
}

// WriteToRequest writes these params to a swagger request
func (o *GetUsedByAppResourcesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AppID != nil {

		// query param appId
		var qrAppID int32
		if o.AppID != nil {
			qrAppID = *o.AppID
		}
		qAppID := swag.FormatInt32(qrAppID)
		if qAppID != "" {
			if err := r.SetQueryParam("appId", qAppID); err != nil {
				return err
			}
		}

	}

	// path param user
	if err := r.SetPathParam("user", o.User); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
