// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cli/models"
)

// AddConfigFileReader is a Reader for the AddConfigFile structure.
type AddConfigFileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddConfigFileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddConfigFileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewAddConfigFileUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewAddConfigFileForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAddConfigFileOK creates a AddConfigFileOK with default headers values
func NewAddConfigFileOK() *AddConfigFileOK {
	return &AddConfigFileOK{}
}

/*AddConfigFileOK handles this case with default header values.

Success
*/
type AddConfigFileOK struct {
	Payload *models.ApplicationConfigFileDto
}

func (o *AddConfigFileOK) Error() string {
	return fmt.Sprintf("[POST /api/application/{id}/config-files][%d] addConfigFileOK  %+v", 200, o.Payload)
}

func (o *AddConfigFileOK) GetPayload() *models.ApplicationConfigFileDto {
	return o.Payload
}

func (o *AddConfigFileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApplicationConfigFileDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddConfigFileUnauthorized creates a AddConfigFileUnauthorized with default headers values
func NewAddConfigFileUnauthorized() *AddConfigFileUnauthorized {
	return &AddConfigFileUnauthorized{}
}

/*AddConfigFileUnauthorized handles this case with default header values.

Unauthorized
*/
type AddConfigFileUnauthorized struct {
}

func (o *AddConfigFileUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/application/{id}/config-files][%d] addConfigFileUnauthorized ", 401)
}

func (o *AddConfigFileUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddConfigFileForbidden creates a AddConfigFileForbidden with default headers values
func NewAddConfigFileForbidden() *AddConfigFileForbidden {
	return &AddConfigFileForbidden{}
}

/*AddConfigFileForbidden handles this case with default header values.

Forbidden
*/
type AddConfigFileForbidden struct {
}

func (o *AddConfigFileForbidden) Error() string {
	return fmt.Sprintf("[POST /api/application/{id}/config-files][%d] addConfigFileForbidden ", 403)
}

func (o *AddConfigFileForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
