// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"cli/models"
)

// NewAddVolumeParams creates a new AddVolumeParams object
// with the default values initialized.
func NewAddVolumeParams() *AddVolumeParams {
	var ()
	return &AddVolumeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddVolumeParamsWithTimeout creates a new AddVolumeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddVolumeParamsWithTimeout(timeout time.Duration) *AddVolumeParams {
	var ()
	return &AddVolumeParams{

		timeout: timeout,
	}
}

// NewAddVolumeParamsWithContext creates a new AddVolumeParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddVolumeParamsWithContext(ctx context.Context) *AddVolumeParams {
	var ()
	return &AddVolumeParams{

		Context: ctx,
	}
}

// NewAddVolumeParamsWithHTTPClient creates a new AddVolumeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddVolumeParamsWithHTTPClient(client *http.Client) *AddVolumeParams {
	var ()
	return &AddVolumeParams{
		HTTPClient: client,
	}
}

/*AddVolumeParams contains all the parameters to send to the API endpoint
for the add volume operation typically these are written to a http.Request
*/
type AddVolumeParams struct {

	/*Data*/
	Data *models.ApplicationVolumeDto
	/*ID*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add volume params
func (o *AddVolumeParams) WithTimeout(timeout time.Duration) *AddVolumeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add volume params
func (o *AddVolumeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add volume params
func (o *AddVolumeParams) WithContext(ctx context.Context) *AddVolumeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add volume params
func (o *AddVolumeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add volume params
func (o *AddVolumeParams) WithHTTPClient(client *http.Client) *AddVolumeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add volume params
func (o *AddVolumeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the add volume params
func (o *AddVolumeParams) WithData(data *models.ApplicationVolumeDto) *AddVolumeParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the add volume params
func (o *AddVolumeParams) SetData(data *models.ApplicationVolumeDto) {
	o.Data = data
}

// WithID adds the id to the add volume params
func (o *AddVolumeParams) WithID(id int32) *AddVolumeParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the add volume params
func (o *AddVolumeParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *AddVolumeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
