// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteConfigFileParams creates a new DeleteConfigFileParams object
// with the default values initialized.
func NewDeleteConfigFileParams() *DeleteConfigFileParams {
	var ()
	return &DeleteConfigFileParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteConfigFileParamsWithTimeout creates a new DeleteConfigFileParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteConfigFileParamsWithTimeout(timeout time.Duration) *DeleteConfigFileParams {
	var ()
	return &DeleteConfigFileParams{

		timeout: timeout,
	}
}

// NewDeleteConfigFileParamsWithContext creates a new DeleteConfigFileParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteConfigFileParamsWithContext(ctx context.Context) *DeleteConfigFileParams {
	var ()
	return &DeleteConfigFileParams{

		Context: ctx,
	}
}

// NewDeleteConfigFileParamsWithHTTPClient creates a new DeleteConfigFileParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteConfigFileParamsWithHTTPClient(client *http.Client) *DeleteConfigFileParams {
	var ()
	return &DeleteConfigFileParams{
		HTTPClient: client,
	}
}

/*DeleteConfigFileParams contains all the parameters to send to the API endpoint
for the delete config file operation typically these are written to a http.Request
*/
type DeleteConfigFileParams struct {

	/*ConfigFileID*/
	ConfigFileID int32
	/*ID*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete config file params
func (o *DeleteConfigFileParams) WithTimeout(timeout time.Duration) *DeleteConfigFileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete config file params
func (o *DeleteConfigFileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete config file params
func (o *DeleteConfigFileParams) WithContext(ctx context.Context) *DeleteConfigFileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete config file params
func (o *DeleteConfigFileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete config file params
func (o *DeleteConfigFileParams) WithHTTPClient(client *http.Client) *DeleteConfigFileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete config file params
func (o *DeleteConfigFileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConfigFileID adds the configFileID to the delete config file params
func (o *DeleteConfigFileParams) WithConfigFileID(configFileID int32) *DeleteConfigFileParams {
	o.SetConfigFileID(configFileID)
	return o
}

// SetConfigFileID adds the configFileId to the delete config file params
func (o *DeleteConfigFileParams) SetConfigFileID(configFileID int32) {
	o.ConfigFileID = configFileID
}

// WithID adds the id to the delete config file params
func (o *DeleteConfigFileParams) WithID(id int32) *DeleteConfigFileParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete config file params
func (o *DeleteConfigFileParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteConfigFileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param configFileId
	if err := r.SetPathParam("configFileId", swag.FormatInt32(o.ConfigFileID)); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
