// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteConfigFileReader is a Reader for the DeleteConfigFile structure.
type DeleteConfigFileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteConfigFileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteConfigFileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteConfigFileUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteConfigFileForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteConfigFileOK creates a DeleteConfigFileOK with default headers values
func NewDeleteConfigFileOK() *DeleteConfigFileOK {
	return &DeleteConfigFileOK{}
}

/*DeleteConfigFileOK handles this case with default header values.

Success
*/
type DeleteConfigFileOK struct {
	Payload bool
}

func (o *DeleteConfigFileOK) Error() string {
	return fmt.Sprintf("[DELETE /api/application/{id}/config-files/{configFileId}][%d] deleteConfigFileOK  %+v", 200, o.Payload)
}

func (o *DeleteConfigFileOK) GetPayload() bool {
	return o.Payload
}

func (o *DeleteConfigFileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteConfigFileUnauthorized creates a DeleteConfigFileUnauthorized with default headers values
func NewDeleteConfigFileUnauthorized() *DeleteConfigFileUnauthorized {
	return &DeleteConfigFileUnauthorized{}
}

/*DeleteConfigFileUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteConfigFileUnauthorized struct {
}

func (o *DeleteConfigFileUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /api/application/{id}/config-files/{configFileId}][%d] deleteConfigFileUnauthorized ", 401)
}

func (o *DeleteConfigFileUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteConfigFileForbidden creates a DeleteConfigFileForbidden with default headers values
func NewDeleteConfigFileForbidden() *DeleteConfigFileForbidden {
	return &DeleteConfigFileForbidden{}
}

/*DeleteConfigFileForbidden handles this case with default header values.

Forbidden
*/
type DeleteConfigFileForbidden struct {
}

func (o *DeleteConfigFileForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/application/{id}/config-files/{configFileId}][%d] deleteConfigFileForbidden ", 403)
}

func (o *DeleteConfigFileForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
