// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewEndpointsParams creates a new EndpointsParams object
// with the default values initialized.
func NewEndpointsParams() *EndpointsParams {
	var ()
	return &EndpointsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEndpointsParamsWithTimeout creates a new EndpointsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEndpointsParamsWithTimeout(timeout time.Duration) *EndpointsParams {
	var ()
	return &EndpointsParams{

		timeout: timeout,
	}
}

// NewEndpointsParamsWithContext creates a new EndpointsParams object
// with the default values initialized, and the ability to set a context for a request
func NewEndpointsParamsWithContext(ctx context.Context) *EndpointsParams {
	var ()
	return &EndpointsParams{

		Context: ctx,
	}
}

// NewEndpointsParamsWithHTTPClient creates a new EndpointsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEndpointsParamsWithHTTPClient(client *http.Client) *EndpointsParams {
	var ()
	return &EndpointsParams{
		HTTPClient: client,
	}
}

/*EndpointsParams contains all the parameters to send to the API endpoint
for the endpoints operation typically these are written to a http.Request
*/
type EndpointsParams struct {

	/*ID*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the endpoints params
func (o *EndpointsParams) WithTimeout(timeout time.Duration) *EndpointsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the endpoints params
func (o *EndpointsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the endpoints params
func (o *EndpointsParams) WithContext(ctx context.Context) *EndpointsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the endpoints params
func (o *EndpointsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the endpoints params
func (o *EndpointsParams) WithHTTPClient(client *http.Client) *EndpointsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the endpoints params
func (o *EndpointsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the endpoints params
func (o *EndpointsParams) WithID(id int32) *EndpointsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the endpoints params
func (o *EndpointsParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *EndpointsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
