// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cli/models"
)

// GetPortsReader is a Reader for the GetPorts structure.
type GetPortsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPortsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPortsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetPortsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetPortsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPortsOK creates a GetPortsOK with default headers values
func NewGetPortsOK() *GetPortsOK {
	return &GetPortsOK{}
}

/*GetPortsOK handles this case with default header values.

Success
*/
type GetPortsOK struct {
	Payload *models.ApplicationPortsBindingDto
}

func (o *GetPortsOK) Error() string {
	return fmt.Sprintf("[GET /api/application/{id}/ports][%d] getPortsOK  %+v", 200, o.Payload)
}

func (o *GetPortsOK) GetPayload() *models.ApplicationPortsBindingDto {
	return o.Payload
}

func (o *GetPortsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApplicationPortsBindingDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPortsUnauthorized creates a GetPortsUnauthorized with default headers values
func NewGetPortsUnauthorized() *GetPortsUnauthorized {
	return &GetPortsUnauthorized{}
}

/*GetPortsUnauthorized handles this case with default header values.

Unauthorized
*/
type GetPortsUnauthorized struct {
}

func (o *GetPortsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/application/{id}/ports][%d] getPortsUnauthorized ", 401)
}

func (o *GetPortsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetPortsForbidden creates a GetPortsForbidden with default headers values
func NewGetPortsForbidden() *GetPortsForbidden {
	return &GetPortsForbidden{}
}

/*GetPortsForbidden handles this case with default header values.

Forbidden
*/
type GetPortsForbidden struct {
}

func (o *GetPortsForbidden) Error() string {
	return fmt.Sprintf("[GET /api/application/{id}/ports][%d] getPortsForbidden ", 403)
}

func (o *GetPortsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
