// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cli/models"
)

// GetEnvVarsReader is a Reader for the GetEnvVars structure.
type GetEnvVarsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetEnvVarsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetEnvVarsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetEnvVarsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetEnvVarsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetEnvVarsOK creates a GetEnvVarsOK with default headers values
func NewGetEnvVarsOK() *GetEnvVarsOK {
	return &GetEnvVarsOK{}
}

/*GetEnvVarsOK handles this case with default header values.

Success
*/
type GetEnvVarsOK struct {
	Payload []*models.ApplicationEnvironmentVariableDto
}

func (o *GetEnvVarsOK) Error() string {
	return fmt.Sprintf("[GET /api/application/{id}/env-vars][%d] getEnvVarsOK  %+v", 200, o.Payload)
}

func (o *GetEnvVarsOK) GetPayload() []*models.ApplicationEnvironmentVariableDto {
	return o.Payload
}

func (o *GetEnvVarsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetEnvVarsUnauthorized creates a GetEnvVarsUnauthorized with default headers values
func NewGetEnvVarsUnauthorized() *GetEnvVarsUnauthorized {
	return &GetEnvVarsUnauthorized{}
}

/*GetEnvVarsUnauthorized handles this case with default header values.

Unauthorized
*/
type GetEnvVarsUnauthorized struct {
}

func (o *GetEnvVarsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/application/{id}/env-vars][%d] getEnvVarsUnauthorized ", 401)
}

func (o *GetEnvVarsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetEnvVarsForbidden creates a GetEnvVarsForbidden with default headers values
func NewGetEnvVarsForbidden() *GetEnvVarsForbidden {
	return &GetEnvVarsForbidden{}
}

/*GetEnvVarsForbidden handles this case with default header values.

Forbidden
*/
type GetEnvVarsForbidden struct {
}

func (o *GetEnvVarsForbidden) Error() string {
	return fmt.Sprintf("[GET /api/application/{id}/env-vars][%d] getEnvVarsForbidden ", 403)
}

func (o *GetEnvVarsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
