// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetPortsParams creates a new GetPortsParams object
// with the default values initialized.
func NewGetPortsParams() *GetPortsParams {
	var ()
	return &GetPortsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPortsParamsWithTimeout creates a new GetPortsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPortsParamsWithTimeout(timeout time.Duration) *GetPortsParams {
	var ()
	return &GetPortsParams{

		timeout: timeout,
	}
}

// NewGetPortsParamsWithContext creates a new GetPortsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPortsParamsWithContext(ctx context.Context) *GetPortsParams {
	var ()
	return &GetPortsParams{

		Context: ctx,
	}
}

// NewGetPortsParamsWithHTTPClient creates a new GetPortsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPortsParamsWithHTTPClient(client *http.Client) *GetPortsParams {
	var ()
	return &GetPortsParams{
		HTTPClient: client,
	}
}

/*GetPortsParams contains all the parameters to send to the API endpoint
for the get ports operation typically these are written to a http.Request
*/
type GetPortsParams struct {

	/*ID*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get ports params
func (o *GetPortsParams) WithTimeout(timeout time.Duration) *GetPortsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get ports params
func (o *GetPortsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get ports params
func (o *GetPortsParams) WithContext(ctx context.Context) *GetPortsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get ports params
func (o *GetPortsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get ports params
func (o *GetPortsParams) WithHTTPClient(client *http.Client) *GetPortsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get ports params
func (o *GetPortsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get ports params
func (o *GetPortsParams) WithID(id int32) *GetPortsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get ports params
func (o *GetPortsParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetPortsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
