// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cli/models"
)

// GetConfigFilesReader is a Reader for the GetConfigFiles structure.
type GetConfigFilesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetConfigFilesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetConfigFilesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetConfigFilesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetConfigFilesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetConfigFilesOK creates a GetConfigFilesOK with default headers values
func NewGetConfigFilesOK() *GetConfigFilesOK {
	return &GetConfigFilesOK{}
}

/*GetConfigFilesOK handles this case with default header values.

Success
*/
type GetConfigFilesOK struct {
	Payload []*models.ApplicationConfigFileDto
}

func (o *GetConfigFilesOK) Error() string {
	return fmt.Sprintf("[GET /api/application/{id}/config-files][%d] getConfigFilesOK  %+v", 200, o.Payload)
}

func (o *GetConfigFilesOK) GetPayload() []*models.ApplicationConfigFileDto {
	return o.Payload
}

func (o *GetConfigFilesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetConfigFilesUnauthorized creates a GetConfigFilesUnauthorized with default headers values
func NewGetConfigFilesUnauthorized() *GetConfigFilesUnauthorized {
	return &GetConfigFilesUnauthorized{}
}

/*GetConfigFilesUnauthorized handles this case with default header values.

Unauthorized
*/
type GetConfigFilesUnauthorized struct {
}

func (o *GetConfigFilesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/application/{id}/config-files][%d] getConfigFilesUnauthorized ", 401)
}

func (o *GetConfigFilesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetConfigFilesForbidden creates a GetConfigFilesForbidden with default headers values
func NewGetConfigFilesForbidden() *GetConfigFilesForbidden {
	return &GetConfigFilesForbidden{}
}

/*GetConfigFilesForbidden handles this case with default header values.

Forbidden
*/
type GetConfigFilesForbidden struct {
}

func (o *GetConfigFilesForbidden) Error() string {
	return fmt.Sprintf("[GET /api/application/{id}/config-files][%d] getConfigFilesForbidden ", 403)
}

func (o *GetConfigFilesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
