// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetEnvVarsParams creates a new GetEnvVarsParams object
// with the default values initialized.
func NewGetEnvVarsParams() *GetEnvVarsParams {
	var ()
	return &GetEnvVarsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetEnvVarsParamsWithTimeout creates a new GetEnvVarsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetEnvVarsParamsWithTimeout(timeout time.Duration) *GetEnvVarsParams {
	var ()
	return &GetEnvVarsParams{

		timeout: timeout,
	}
}

// NewGetEnvVarsParamsWithContext creates a new GetEnvVarsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetEnvVarsParamsWithContext(ctx context.Context) *GetEnvVarsParams {
	var ()
	return &GetEnvVarsParams{

		Context: ctx,
	}
}

// NewGetEnvVarsParamsWithHTTPClient creates a new GetEnvVarsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetEnvVarsParamsWithHTTPClient(client *http.Client) *GetEnvVarsParams {
	var ()
	return &GetEnvVarsParams{
		HTTPClient: client,
	}
}

/*GetEnvVarsParams contains all the parameters to send to the API endpoint
for the get env vars operation typically these are written to a http.Request
*/
type GetEnvVarsParams struct {

	/*ID*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get env vars params
func (o *GetEnvVarsParams) WithTimeout(timeout time.Duration) *GetEnvVarsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get env vars params
func (o *GetEnvVarsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get env vars params
func (o *GetEnvVarsParams) WithContext(ctx context.Context) *GetEnvVarsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get env vars params
func (o *GetEnvVarsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get env vars params
func (o *GetEnvVarsParams) WithHTTPClient(client *http.Client) *GetEnvVarsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get env vars params
func (o *GetEnvVarsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get env vars params
func (o *GetEnvVarsParams) WithID(id int32) *GetEnvVarsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get env vars params
func (o *GetEnvVarsParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetEnvVarsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
