// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cli/models"
)

// GetVolumesReader is a Reader for the GetVolumes structure.
type GetVolumesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetVolumesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetVolumesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetVolumesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetVolumesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetVolumesOK creates a GetVolumesOK with default headers values
func NewGetVolumesOK() *GetVolumesOK {
	return &GetVolumesOK{}
}

/*GetVolumesOK handles this case with default header values.

Success
*/
type GetVolumesOK struct {
	Payload []*models.ApplicationVolumeDto
}

func (o *GetVolumesOK) Error() string {
	return fmt.Sprintf("[GET /api/application/{id}/volume][%d] getVolumesOK  %+v", 200, o.Payload)
}

func (o *GetVolumesOK) GetPayload() []*models.ApplicationVolumeDto {
	return o.Payload
}

func (o *GetVolumesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetVolumesUnauthorized creates a GetVolumesUnauthorized with default headers values
func NewGetVolumesUnauthorized() *GetVolumesUnauthorized {
	return &GetVolumesUnauthorized{}
}

/*GetVolumesUnauthorized handles this case with default header values.

Unauthorized
*/
type GetVolumesUnauthorized struct {
}

func (o *GetVolumesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/application/{id}/volume][%d] getVolumesUnauthorized ", 401)
}

func (o *GetVolumesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetVolumesForbidden creates a GetVolumesForbidden with default headers values
func NewGetVolumesForbidden() *GetVolumesForbidden {
	return &GetVolumesForbidden{}
}

/*GetVolumesForbidden handles this case with default header values.

Forbidden
*/
type GetVolumesForbidden struct {
}

func (o *GetVolumesForbidden) Error() string {
	return fmt.Sprintf("[GET /api/application/{id}/volume][%d] getVolumesForbidden ", 403)
}

func (o *GetVolumesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
