// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewHasEventsParams creates a new HasEventsParams object
// with the default values initialized.
func NewHasEventsParams() *HasEventsParams {
	var ()
	return &HasEventsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewHasEventsParamsWithTimeout creates a new HasEventsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewHasEventsParamsWithTimeout(timeout time.Duration) *HasEventsParams {
	var ()
	return &HasEventsParams{

		timeout: timeout,
	}
}

// NewHasEventsParamsWithContext creates a new HasEventsParams object
// with the default values initialized, and the ability to set a context for a request
func NewHasEventsParamsWithContext(ctx context.Context) *HasEventsParams {
	var ()
	return &HasEventsParams{

		Context: ctx,
	}
}

// NewHasEventsParamsWithHTTPClient creates a new HasEventsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewHasEventsParamsWithHTTPClient(client *http.Client) *HasEventsParams {
	var ()
	return &HasEventsParams{
		HTTPClient: client,
	}
}

/*HasEventsParams contains all the parameters to send to the API endpoint
for the has events operation typically these are written to a http.Request
*/
type HasEventsParams struct {

	/*ID*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the has events params
func (o *HasEventsParams) WithTimeout(timeout time.Duration) *HasEventsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the has events params
func (o *HasEventsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the has events params
func (o *HasEventsParams) WithContext(ctx context.Context) *HasEventsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the has events params
func (o *HasEventsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the has events params
func (o *HasEventsParams) WithHTTPClient(client *http.Client) *HasEventsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the has events params
func (o *HasEventsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the has events params
func (o *HasEventsParams) WithID(id int32) *HasEventsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the has events params
func (o *HasEventsParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *HasEventsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
