// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"cli/models"
)

// NewSetCustomImageParams creates a new SetCustomImageParams object
// with the default values initialized.
func NewSetCustomImageParams() *SetCustomImageParams {
	var ()
	return &SetCustomImageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetCustomImageParamsWithTimeout creates a new SetCustomImageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetCustomImageParamsWithTimeout(timeout time.Duration) *SetCustomImageParams {
	var ()
	return &SetCustomImageParams{

		timeout: timeout,
	}
}

// NewSetCustomImageParamsWithContext creates a new SetCustomImageParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetCustomImageParamsWithContext(ctx context.Context) *SetCustomImageParams {
	var ()
	return &SetCustomImageParams{

		Context: ctx,
	}
}

// NewSetCustomImageParamsWithHTTPClient creates a new SetCustomImageParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetCustomImageParamsWithHTTPClient(client *http.Client) *SetCustomImageParams {
	var ()
	return &SetCustomImageParams{
		HTTPClient: client,
	}
}

/*SetCustomImageParams contains all the parameters to send to the API endpoint
for the set custom image operation typically these are written to a http.Request
*/
type SetCustomImageParams struct {

	/*Data*/
	Data *models.PrivateImageDto
	/*ID*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set custom image params
func (o *SetCustomImageParams) WithTimeout(timeout time.Duration) *SetCustomImageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set custom image params
func (o *SetCustomImageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set custom image params
func (o *SetCustomImageParams) WithContext(ctx context.Context) *SetCustomImageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set custom image params
func (o *SetCustomImageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set custom image params
func (o *SetCustomImageParams) WithHTTPClient(client *http.Client) *SetCustomImageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set custom image params
func (o *SetCustomImageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the set custom image params
func (o *SetCustomImageParams) WithData(data *models.PrivateImageDto) *SetCustomImageParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the set custom image params
func (o *SetCustomImageParams) SetData(data *models.PrivateImageDto) {
	o.Data = data
}

// WithID adds the id to the set custom image params
func (o *SetCustomImageParams) WithID(id int32) *SetCustomImageParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the set custom image params
func (o *SetCustomImageParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *SetCustomImageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
