// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewSetCommandParams creates a new SetCommandParams object
// with the default values initialized.
func NewSetCommandParams() *SetCommandParams {
	var ()
	return &SetCommandParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetCommandParamsWithTimeout creates a new SetCommandParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetCommandParamsWithTimeout(timeout time.Duration) *SetCommandParams {
	var ()
	return &SetCommandParams{

		timeout: timeout,
	}
}

// NewSetCommandParamsWithContext creates a new SetCommandParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetCommandParamsWithContext(ctx context.Context) *SetCommandParams {
	var ()
	return &SetCommandParams{

		Context: ctx,
	}
}

// NewSetCommandParamsWithHTTPClient creates a new SetCommandParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetCommandParamsWithHTTPClient(client *http.Client) *SetCommandParams {
	var ()
	return &SetCommandParams{
		HTTPClient: client,
	}
}

/*SetCommandParams contains all the parameters to send to the API endpoint
for the set command operation typically these are written to a http.Request
*/
type SetCommandParams struct {

	/*Command*/
	Command string
	/*ID*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set command params
func (o *SetCommandParams) WithTimeout(timeout time.Duration) *SetCommandParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set command params
func (o *SetCommandParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set command params
func (o *SetCommandParams) WithContext(ctx context.Context) *SetCommandParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set command params
func (o *SetCommandParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set command params
func (o *SetCommandParams) WithHTTPClient(client *http.Client) *SetCommandParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set command params
func (o *SetCommandParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCommand adds the command to the set command params
func (o *SetCommandParams) WithCommand(command string) *SetCommandParams {
	o.SetCommand(command)
	return o
}

// SetCommand adds the command to the set command params
func (o *SetCommandParams) SetCommand(command string) {
	o.Command = command
}

// WithID adds the id to the set command params
func (o *SetCommandParams) WithID(id int32) *SetCommandParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the set command params
func (o *SetCommandParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *SetCommandParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Command); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
