// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SetCommandReader is a Reader for the SetCommand structure.
type SetCommandReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetCommandReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSetCommandOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewSetCommandUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewSetCommandForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSetCommandOK creates a SetCommandOK with default headers values
func NewSetCommandOK() *SetCommandOK {
	return &SetCommandOK{}
}

/*SetCommandOK handles this case with default header values.

Success
*/
type SetCommandOK struct {
}

func (o *SetCommandOK) Error() string {
	return fmt.Sprintf("[POST /api/application/{id}/set-command][%d] setCommandOK ", 200)
}

func (o *SetCommandOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSetCommandUnauthorized creates a SetCommandUnauthorized with default headers values
func NewSetCommandUnauthorized() *SetCommandUnauthorized {
	return &SetCommandUnauthorized{}
}

/*SetCommandUnauthorized handles this case with default header values.

Unauthorized
*/
type SetCommandUnauthorized struct {
}

func (o *SetCommandUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/application/{id}/set-command][%d] setCommandUnauthorized ", 401)
}

func (o *SetCommandUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSetCommandForbidden creates a SetCommandForbidden with default headers values
func NewSetCommandForbidden() *SetCommandForbidden {
	return &SetCommandForbidden{}
}

/*SetCommandForbidden handles this case with default header values.

Forbidden
*/
type SetCommandForbidden struct {
}

func (o *SetCommandForbidden) Error() string {
	return fmt.Sprintf("[POST /api/application/{id}/set-command][%d] setCommandForbidden ", 403)
}

func (o *SetCommandForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
