// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"cli/models"
)

// NewSetPortsParams creates a new SetPortsParams object
// with the default values initialized.
func NewSetPortsParams() *SetPortsParams {
	var ()
	return &SetPortsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetPortsParamsWithTimeout creates a new SetPortsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetPortsParamsWithTimeout(timeout time.Duration) *SetPortsParams {
	var ()
	return &SetPortsParams{

		timeout: timeout,
	}
}

// NewSetPortsParamsWithContext creates a new SetPortsParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetPortsParamsWithContext(ctx context.Context) *SetPortsParams {
	var ()
	return &SetPortsParams{

		Context: ctx,
	}
}

// NewSetPortsParamsWithHTTPClient creates a new SetPortsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetPortsParamsWithHTTPClient(client *http.Client) *SetPortsParams {
	var ()
	return &SetPortsParams{
		HTTPClient: client,
	}
}

/*SetPortsParams contains all the parameters to send to the API endpoint
for the set ports operation typically these are written to a http.Request
*/
type SetPortsParams struct {

	/*ID*/
	ID int32
	/*Ports*/
	Ports *models.ApplicationPortsBindingDto

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set ports params
func (o *SetPortsParams) WithTimeout(timeout time.Duration) *SetPortsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set ports params
func (o *SetPortsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set ports params
func (o *SetPortsParams) WithContext(ctx context.Context) *SetPortsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set ports params
func (o *SetPortsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set ports params
func (o *SetPortsParams) WithHTTPClient(client *http.Client) *SetPortsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set ports params
func (o *SetPortsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the set ports params
func (o *SetPortsParams) WithID(id int32) *SetPortsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the set ports params
func (o *SetPortsParams) SetID(id int32) {
	o.ID = id
}

// WithPorts adds the ports to the set ports params
func (o *SetPortsParams) WithPorts(ports *models.ApplicationPortsBindingDto) *SetPortsParams {
	o.SetPorts(ports)
	return o
}

// SetPorts adds the ports to the set ports params
func (o *SetPortsParams) SetPorts(ports *models.ApplicationPortsBindingDto) {
	o.Ports = ports
}

// WriteToRequest writes these params to a swagger request
func (o *SetPortsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if o.Ports != nil {
		if err := r.SetBodyParam(o.Ports); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
