// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// StopReader is a Reader for the Stop structure.
type StopReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStopOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewStopUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewStopForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewStopOK creates a StopOK with default headers values
func NewStopOK() *StopOK {
	return &StopOK{}
}

/*StopOK handles this case with default header values.

Success
*/
type StopOK struct {
}

func (o *StopOK) Error() string {
	return fmt.Sprintf("[PUT /api/application/{id}/stop][%d] stopOK ", 200)
}

func (o *StopOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewStopUnauthorized creates a StopUnauthorized with default headers values
func NewStopUnauthorized() *StopUnauthorized {
	return &StopUnauthorized{}
}

/*StopUnauthorized handles this case with default header values.

Unauthorized
*/
type StopUnauthorized struct {
}

func (o *StopUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /api/application/{id}/stop][%d] stopUnauthorized ", 401)
}

func (o *StopUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewStopForbidden creates a StopForbidden with default headers values
func NewStopForbidden() *StopForbidden {
	return &StopForbidden{}
}

/*StopForbidden handles this case with default header values.

Forbidden
*/
type StopForbidden struct {
}

func (o *StopForbidden) Error() string {
	return fmt.Sprintf("[PUT /api/application/{id}/stop][%d] stopForbidden ", 403)
}

func (o *StopForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
