// Code generated by go-swagger; DO NOT EDIT.

package billing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cli/models"
)

// GetAllPlansReader is a Reader for the GetAllPlans structure.
type GetAllPlansReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllPlansReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAllPlansOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetAllPlansUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAllPlansForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAllPlansOK creates a GetAllPlansOK with default headers values
func NewGetAllPlansOK() *GetAllPlansOK {
	return &GetAllPlansOK{}
}

/*GetAllPlansOK handles this case with default header values.

Success
*/
type GetAllPlansOK struct {
	Payload *models.PlanDto
}

func (o *GetAllPlansOK) Error() string {
	return fmt.Sprintf("[GET /api/billing/plans][%d] getAllPlansOK  %+v", 200, o.Payload)
}

func (o *GetAllPlansOK) GetPayload() *models.PlanDto {
	return o.Payload
}

func (o *GetAllPlansOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PlanDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllPlansUnauthorized creates a GetAllPlansUnauthorized with default headers values
func NewGetAllPlansUnauthorized() *GetAllPlansUnauthorized {
	return &GetAllPlansUnauthorized{}
}

/*GetAllPlansUnauthorized handles this case with default header values.

Unauthorized
*/
type GetAllPlansUnauthorized struct {
}

func (o *GetAllPlansUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/billing/plans][%d] getAllPlansUnauthorized ", 401)
}

func (o *GetAllPlansUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAllPlansForbidden creates a GetAllPlansForbidden with default headers values
func NewGetAllPlansForbidden() *GetAllPlansForbidden {
	return &GetAllPlansForbidden{}
}

/*GetAllPlansForbidden handles this case with default header values.

Forbidden
*/
type GetAllPlansForbidden struct {
}

func (o *GetAllPlansForbidden) Error() string {
	return fmt.Sprintf("[GET /api/billing/plans][%d] getAllPlansForbidden ", 403)
}

func (o *GetAllPlansForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
