// Code generated by go-swagger; DO NOT EDIT.

package billing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cli/models"
)

// ModifyUserReader is a Reader for the ModifyUser structure.
type ModifyUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ModifyUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewModifyUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewModifyUserUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewModifyUserForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewModifyUserOK creates a ModifyUserOK with default headers values
func NewModifyUserOK() *ModifyUserOK {
	return &ModifyUserOK{}
}

/*ModifyUserOK handles this case with default header values.

Success
*/
type ModifyUserOK struct {
	Payload *models.BillingUserInfoDto
}

func (o *ModifyUserOK) Error() string {
	return fmt.Sprintf("[PUT /api/billing/{userId}/modify-balance/{amount}][%d] modifyUserOK  %+v", 200, o.Payload)
}

func (o *ModifyUserOK) GetPayload() *models.BillingUserInfoDto {
	return o.Payload
}

func (o *ModifyUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BillingUserInfoDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewModifyUserUnauthorized creates a ModifyUserUnauthorized with default headers values
func NewModifyUserUnauthorized() *ModifyUserUnauthorized {
	return &ModifyUserUnauthorized{}
}

/*ModifyUserUnauthorized handles this case with default header values.

Unauthorized
*/
type ModifyUserUnauthorized struct {
}

func (o *ModifyUserUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /api/billing/{userId}/modify-balance/{amount}][%d] modifyUserUnauthorized ", 401)
}

func (o *ModifyUserUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewModifyUserForbidden creates a ModifyUserForbidden with default headers values
func NewModifyUserForbidden() *ModifyUserForbidden {
	return &ModifyUserForbidden{}
}

/*ModifyUserForbidden handles this case with default header values.

Forbidden
*/
type ModifyUserForbidden struct {
}

func (o *ModifyUserForbidden) Error() string {
	return fmt.Sprintf("[PUT /api/billing/{userId}/modify-balance/{amount}][%d] modifyUserForbidden ", 403)
}

func (o *ModifyUserForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
