// Code generated by go-swagger; DO NOT EDIT.

package billing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewRobokassaSignatureParams creates a new RobokassaSignatureParams object
// with the default values initialized.
func NewRobokassaSignatureParams() *RobokassaSignatureParams {
	var ()
	return &RobokassaSignatureParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRobokassaSignatureParamsWithTimeout creates a new RobokassaSignatureParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRobokassaSignatureParamsWithTimeout(timeout time.Duration) *RobokassaSignatureParams {
	var ()
	return &RobokassaSignatureParams{

		timeout: timeout,
	}
}

// NewRobokassaSignatureParamsWithContext creates a new RobokassaSignatureParams object
// with the default values initialized, and the ability to set a context for a request
func NewRobokassaSignatureParamsWithContext(ctx context.Context) *RobokassaSignatureParams {
	var ()
	return &RobokassaSignatureParams{

		Context: ctx,
	}
}

// NewRobokassaSignatureParamsWithHTTPClient creates a new RobokassaSignatureParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRobokassaSignatureParamsWithHTTPClient(client *http.Client) *RobokassaSignatureParams {
	var ()
	return &RobokassaSignatureParams{
		HTTPClient: client,
	}
}

/*RobokassaSignatureParams contains all the parameters to send to the API endpoint
for the robokassa signature operation typically these are written to a http.Request
*/
type RobokassaSignatureParams struct {

	/*OutSum*/
	OutSum int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the robokassa signature params
func (o *RobokassaSignatureParams) WithTimeout(timeout time.Duration) *RobokassaSignatureParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the robokassa signature params
func (o *RobokassaSignatureParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the robokassa signature params
func (o *RobokassaSignatureParams) WithContext(ctx context.Context) *RobokassaSignatureParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the robokassa signature params
func (o *RobokassaSignatureParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the robokassa signature params
func (o *RobokassaSignatureParams) WithHTTPClient(client *http.Client) *RobokassaSignatureParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the robokassa signature params
func (o *RobokassaSignatureParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOutSum adds the outSum to the robokassa signature params
func (o *RobokassaSignatureParams) WithOutSum(outSum int32) *RobokassaSignatureParams {
	o.SetOutSum(outSum)
	return o
}

// SetOutSum adds the outSum to the robokassa signature params
func (o *RobokassaSignatureParams) SetOutSum(outSum int32) {
	o.OutSum = outSum
}

// WriteToRequest writes these params to a swagger request
func (o *RobokassaSignatureParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param outSum
	if err := r.SetPathParam("outSum", swag.FormatInt32(o.OutSum)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
