// Code generated by go-swagger; DO NOT EDIT.

package billing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// RobokassaSignatureReader is a Reader for the RobokassaSignature structure.
type RobokassaSignatureReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RobokassaSignatureReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRobokassaSignatureOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewRobokassaSignatureUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewRobokassaSignatureForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRobokassaSignatureOK creates a RobokassaSignatureOK with default headers values
func NewRobokassaSignatureOK() *RobokassaSignatureOK {
	return &RobokassaSignatureOK{}
}

/*RobokassaSignatureOK handles this case with default header values.

Success
*/
type RobokassaSignatureOK struct {
	Payload string
}

func (o *RobokassaSignatureOK) Error() string {
	return fmt.Sprintf("[GET /api/billing/robokassa-signature/{outSum}][%d] robokassaSignatureOK  %+v", 200, o.Payload)
}

func (o *RobokassaSignatureOK) GetPayload() string {
	return o.Payload
}

func (o *RobokassaSignatureOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRobokassaSignatureUnauthorized creates a RobokassaSignatureUnauthorized with default headers values
func NewRobokassaSignatureUnauthorized() *RobokassaSignatureUnauthorized {
	return &RobokassaSignatureUnauthorized{}
}

/*RobokassaSignatureUnauthorized handles this case with default header values.

Unauthorized
*/
type RobokassaSignatureUnauthorized struct {
}

func (o *RobokassaSignatureUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/billing/robokassa-signature/{outSum}][%d] robokassaSignatureUnauthorized ", 401)
}

func (o *RobokassaSignatureUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRobokassaSignatureForbidden creates a RobokassaSignatureForbidden with default headers values
func NewRobokassaSignatureForbidden() *RobokassaSignatureForbidden {
	return &RobokassaSignatureForbidden{}
}

/*RobokassaSignatureForbidden handles this case with default header values.

Forbidden
*/
type RobokassaSignatureForbidden struct {
}

func (o *RobokassaSignatureForbidden) Error() string {
	return fmt.Sprintf("[GET /api/billing/robokassa-signature/{outSum}][%d] robokassaSignatureForbidden ", 403)
}

func (o *RobokassaSignatureForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
