// Code generated by go-swagger; DO NOT EDIT.

package billing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// RobokassaCallbackReader is a Reader for the RobokassaCallback structure.
type RobokassaCallbackReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RobokassaCallbackReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRobokassaCallbackOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewRobokassaCallbackUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewRobokassaCallbackForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRobokassaCallbackOK creates a RobokassaCallbackOK with default headers values
func NewRobokassaCallbackOK() *RobokassaCallbackOK {
	return &RobokassaCallbackOK{}
}

/*RobokassaCallbackOK handles this case with default header values.

Success
*/
type RobokassaCallbackOK struct {
}

func (o *RobokassaCallbackOK) Error() string {
	return fmt.Sprintf("[GET /api/billing/robokassa-callback][%d] robokassaCallbackOK ", 200)
}

func (o *RobokassaCallbackOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRobokassaCallbackUnauthorized creates a RobokassaCallbackUnauthorized with default headers values
func NewRobokassaCallbackUnauthorized() *RobokassaCallbackUnauthorized {
	return &RobokassaCallbackUnauthorized{}
}

/*RobokassaCallbackUnauthorized handles this case with default header values.

Unauthorized
*/
type RobokassaCallbackUnauthorized struct {
}

func (o *RobokassaCallbackUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/billing/robokassa-callback][%d] robokassaCallbackUnauthorized ", 401)
}

func (o *RobokassaCallbackUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRobokassaCallbackForbidden creates a RobokassaCallbackForbidden with default headers values
func NewRobokassaCallbackForbidden() *RobokassaCallbackForbidden {
	return &RobokassaCallbackForbidden{}
}

/*RobokassaCallbackForbidden handles this case with default header values.

Forbidden
*/
type RobokassaCallbackForbidden struct {
}

func (o *RobokassaCallbackForbidden) Error() string {
	return fmt.Sprintf("[GET /api/billing/robokassa-callback][%d] robokassaCallbackForbidden ", 403)
}

func (o *RobokassaCallbackForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
