// Code generated by go-swagger; DO NOT EDIT.

package billing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SetPlanReader is a Reader for the SetPlan structure.
type SetPlanReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetPlanReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSetPlanOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewSetPlanUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewSetPlanForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSetPlanOK creates a SetPlanOK with default headers values
func NewSetPlanOK() *SetPlanOK {
	return &SetPlanOK{}
}

/*SetPlanOK handles this case with default header values.

Success
*/
type SetPlanOK struct {
}

func (o *SetPlanOK) Error() string {
	return fmt.Sprintf("[PUT /api/billing/{userId}/set-plan/{planName}][%d] setPlanOK ", 200)
}

func (o *SetPlanOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSetPlanUnauthorized creates a SetPlanUnauthorized with default headers values
func NewSetPlanUnauthorized() *SetPlanUnauthorized {
	return &SetPlanUnauthorized{}
}

/*SetPlanUnauthorized handles this case with default header values.

Unauthorized
*/
type SetPlanUnauthorized struct {
}

func (o *SetPlanUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /api/billing/{userId}/set-plan/{planName}][%d] setPlanUnauthorized ", 401)
}

func (o *SetPlanUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSetPlanForbidden creates a SetPlanForbidden with default headers values
func NewSetPlanForbidden() *SetPlanForbidden {
	return &SetPlanForbidden{}
}

/*SetPlanForbidden handles this case with default header values.

Forbidden
*/
type SetPlanForbidden struct {
}

func (o *SetPlanForbidden) Error() string {
	return fmt.Sprintf("[PUT /api/billing/{userId}/set-plan/{planName}][%d] setPlanForbidden ", 403)
}

func (o *SetPlanForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
