// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cli/models"
)

// CreateArchiveReader is a Reader for the CreateArchive structure.
type CreateArchiveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateArchiveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateArchiveOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateArchiveUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateArchiveForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateArchiveOK creates a CreateArchiveOK with default headers values
func NewCreateArchiveOK() *CreateArchiveOK {
	return &CreateArchiveOK{}
}

/*CreateArchiveOK handles this case with default header values.

Success
*/
type CreateArchiveOK struct {
	Payload *models.FileDto
}

func (o *CreateArchiveOK) Error() string {
	return fmt.Sprintf("[POST /api/file/archive][%d] createArchiveOK  %+v", 200, o.Payload)
}

func (o *CreateArchiveOK) GetPayload() *models.FileDto {
	return o.Payload
}

func (o *CreateArchiveOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FileDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateArchiveUnauthorized creates a CreateArchiveUnauthorized with default headers values
func NewCreateArchiveUnauthorized() *CreateArchiveUnauthorized {
	return &CreateArchiveUnauthorized{}
}

/*CreateArchiveUnauthorized handles this case with default header values.

Unauthorized
*/
type CreateArchiveUnauthorized struct {
}

func (o *CreateArchiveUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/file/archive][%d] createArchiveUnauthorized ", 401)
}

func (o *CreateArchiveUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateArchiveForbidden creates a CreateArchiveForbidden with default headers values
func NewCreateArchiveForbidden() *CreateArchiveForbidden {
	return &CreateArchiveForbidden{}
}

/*CreateArchiveForbidden handles this case with default header values.

Forbidden
*/
type CreateArchiveForbidden struct {
}

func (o *CreateArchiveForbidden) Error() string {
	return fmt.Sprintf("[POST /api/file/archive][%d] createArchiveForbidden ", 403)
}

func (o *CreateArchiveForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
