// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetFileParams creates a new GetFileParams object
// with the default values initialized.
func NewGetFileParams() *GetFileParams {
	var ()
	return &GetFileParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetFileParamsWithTimeout creates a new GetFileParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetFileParamsWithTimeout(timeout time.Duration) *GetFileParams {
	var ()
	return &GetFileParams{

		timeout: timeout,
	}
}

// NewGetFileParamsWithContext creates a new GetFileParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetFileParamsWithContext(ctx context.Context) *GetFileParams {
	var ()
	return &GetFileParams{

		Context: ctx,
	}
}

// NewGetFileParamsWithHTTPClient creates a new GetFileParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetFileParamsWithHTTPClient(client *http.Client) *GetFileParams {
	var ()
	return &GetFileParams{
		HTTPClient: client,
	}
}

/*GetFileParams contains all the parameters to send to the API endpoint
for the get file operation typically these are written to a http.Request
*/
type GetFileParams struct {

	/*Fid*/
	Fid int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get file params
func (o *GetFileParams) WithTimeout(timeout time.Duration) *GetFileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get file params
func (o *GetFileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get file params
func (o *GetFileParams) WithContext(ctx context.Context) *GetFileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get file params
func (o *GetFileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get file params
func (o *GetFileParams) WithHTTPClient(client *http.Client) *GetFileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get file params
func (o *GetFileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFid adds the fid to the get file params
func (o *GetFileParams) WithFid(fid int32) *GetFileParams {
	o.SetFid(fid)
	return o
}

// SetFid adds the fid to the get file params
func (o *GetFileParams) SetFid(fid int32) {
	o.Fid = fid
}

// WriteToRequest writes these params to a swagger request
func (o *GetFileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param fid
	if err := r.SetPathParam("fid", swag.FormatInt32(o.Fid)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
