// Code generated by go-swagger; DO NOT EDIT.

package admin_setting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cli/models"
)

// CreateKubeClusterReader is a Reader for the CreateKubeCluster structure.
type CreateKubeClusterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateKubeClusterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateKubeClusterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateKubeClusterUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateKubeClusterForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateKubeClusterOK creates a CreateKubeClusterOK with default headers values
func NewCreateKubeClusterOK() *CreateKubeClusterOK {
	return &CreateKubeClusterOK{}
}

/*CreateKubeClusterOK handles this case with default header values.

Success
*/
type CreateKubeClusterOK struct {
	Payload *models.KubernetesClusterSummaryDto
}

func (o *CreateKubeClusterOK) Error() string {
	return fmt.Sprintf("[POST /api/admin/clusters/k8s][%d] createKubeClusterOK  %+v", 200, o.Payload)
}

func (o *CreateKubeClusterOK) GetPayload() *models.KubernetesClusterSummaryDto {
	return o.Payload
}

func (o *CreateKubeClusterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.KubernetesClusterSummaryDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateKubeClusterUnauthorized creates a CreateKubeClusterUnauthorized with default headers values
func NewCreateKubeClusterUnauthorized() *CreateKubeClusterUnauthorized {
	return &CreateKubeClusterUnauthorized{}
}

/*CreateKubeClusterUnauthorized handles this case with default header values.

Unauthorized
*/
type CreateKubeClusterUnauthorized struct {
}

func (o *CreateKubeClusterUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/admin/clusters/k8s][%d] createKubeClusterUnauthorized ", 401)
}

func (o *CreateKubeClusterUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateKubeClusterForbidden creates a CreateKubeClusterForbidden with default headers values
func NewCreateKubeClusterForbidden() *CreateKubeClusterForbidden {
	return &CreateKubeClusterForbidden{}
}

/*CreateKubeClusterForbidden handles this case with default header values.

Forbidden
*/
type CreateKubeClusterForbidden struct {
}

func (o *CreateKubeClusterForbidden) Error() string {
	return fmt.Sprintf("[POST /api/admin/clusters/k8s][%d] createKubeClusterForbidden ", 403)
}

func (o *CreateKubeClusterForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
