// Code generated by go-swagger; DO NOT EDIT.

package admin_setting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteKubeClusterReader is a Reader for the DeleteKubeCluster structure.
type DeleteKubeClusterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteKubeClusterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteKubeClusterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteKubeClusterUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteKubeClusterForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteKubeClusterOK creates a DeleteKubeClusterOK with default headers values
func NewDeleteKubeClusterOK() *DeleteKubeClusterOK {
	return &DeleteKubeClusterOK{}
}

/*DeleteKubeClusterOK handles this case with default header values.

Success
*/
type DeleteKubeClusterOK struct {
}

func (o *DeleteKubeClusterOK) Error() string {
	return fmt.Sprintf("[DELETE /api/admin/clusters/k8s/{id}][%d] deleteKubeClusterOK ", 200)
}

func (o *DeleteKubeClusterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteKubeClusterUnauthorized creates a DeleteKubeClusterUnauthorized with default headers values
func NewDeleteKubeClusterUnauthorized() *DeleteKubeClusterUnauthorized {
	return &DeleteKubeClusterUnauthorized{}
}

/*DeleteKubeClusterUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteKubeClusterUnauthorized struct {
}

func (o *DeleteKubeClusterUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /api/admin/clusters/k8s/{id}][%d] deleteKubeClusterUnauthorized ", 401)
}

func (o *DeleteKubeClusterUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteKubeClusterForbidden creates a DeleteKubeClusterForbidden with default headers values
func NewDeleteKubeClusterForbidden() *DeleteKubeClusterForbidden {
	return &DeleteKubeClusterForbidden{}
}

/*DeleteKubeClusterForbidden handles this case with default header values.

Forbidden
*/
type DeleteKubeClusterForbidden struct {
}

func (o *DeleteKubeClusterForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/admin/clusters/k8s/{id}][%d] deleteKubeClusterForbidden ", 403)
}

func (o *DeleteKubeClusterForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
