// Code generated by go-swagger; DO NOT EDIT.

package admin_setting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewFixUserNullPlanParams creates a new FixUserNullPlanParams object
// with the default values initialized.
func NewFixUserNullPlanParams() *FixUserNullPlanParams {

	return &FixUserNullPlanParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFixUserNullPlanParamsWithTimeout creates a new FixUserNullPlanParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFixUserNullPlanParamsWithTimeout(timeout time.Duration) *FixUserNullPlanParams {

	return &FixUserNullPlanParams{

		timeout: timeout,
	}
}

// NewFixUserNullPlanParamsWithContext creates a new FixUserNullPlanParams object
// with the default values initialized, and the ability to set a context for a request
func NewFixUserNullPlanParamsWithContext(ctx context.Context) *FixUserNullPlanParams {

	return &FixUserNullPlanParams{

		Context: ctx,
	}
}

// NewFixUserNullPlanParamsWithHTTPClient creates a new FixUserNullPlanParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFixUserNullPlanParamsWithHTTPClient(client *http.Client) *FixUserNullPlanParams {

	return &FixUserNullPlanParams{
		HTTPClient: client,
	}
}

/*FixUserNullPlanParams contains all the parameters to send to the API endpoint
for the fix user null plan operation typically these are written to a http.Request
*/
type FixUserNullPlanParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the fix user null plan params
func (o *FixUserNullPlanParams) WithTimeout(timeout time.Duration) *FixUserNullPlanParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the fix user null plan params
func (o *FixUserNullPlanParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the fix user null plan params
func (o *FixUserNullPlanParams) WithContext(ctx context.Context) *FixUserNullPlanParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the fix user null plan params
func (o *FixUserNullPlanParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the fix user null plan params
func (o *FixUserNullPlanParams) WithHTTPClient(client *http.Client) *FixUserNullPlanParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the fix user null plan params
func (o *FixUserNullPlanParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *FixUserNullPlanParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
