// Code generated by go-swagger; DO NOT EDIT.

package admin_setting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetKubeClustersParams creates a new GetKubeClustersParams object
// with the default values initialized.
func NewGetKubeClustersParams() *GetKubeClustersParams {

	return &GetKubeClustersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetKubeClustersParamsWithTimeout creates a new GetKubeClustersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetKubeClustersParamsWithTimeout(timeout time.Duration) *GetKubeClustersParams {

	return &GetKubeClustersParams{

		timeout: timeout,
	}
}

// NewGetKubeClustersParamsWithContext creates a new GetKubeClustersParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetKubeClustersParamsWithContext(ctx context.Context) *GetKubeClustersParams {

	return &GetKubeClustersParams{

		Context: ctx,
	}
}

// NewGetKubeClustersParamsWithHTTPClient creates a new GetKubeClustersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetKubeClustersParamsWithHTTPClient(client *http.Client) *GetKubeClustersParams {

	return &GetKubeClustersParams{
		HTTPClient: client,
	}
}

/*GetKubeClustersParams contains all the parameters to send to the API endpoint
for the get kube clusters operation typically these are written to a http.Request
*/
type GetKubeClustersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get kube clusters params
func (o *GetKubeClustersParams) WithTimeout(timeout time.Duration) *GetKubeClustersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get kube clusters params
func (o *GetKubeClustersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get kube clusters params
func (o *GetKubeClustersParams) WithContext(ctx context.Context) *GetKubeClustersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get kube clusters params
func (o *GetKubeClustersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get kube clusters params
func (o *GetKubeClustersParams) WithHTTPClient(client *http.Client) *GetKubeClustersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get kube clusters params
func (o *GetKubeClustersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetKubeClustersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
