// Code generated by go-swagger; DO NOT EDIT.

package admin_setting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cli/models"
)

// GetDockerRegistriesReader is a Reader for the GetDockerRegistries structure.
type GetDockerRegistriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDockerRegistriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDockerRegistriesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetDockerRegistriesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetDockerRegistriesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDockerRegistriesOK creates a GetDockerRegistriesOK with default headers values
func NewGetDockerRegistriesOK() *GetDockerRegistriesOK {
	return &GetDockerRegistriesOK{}
}

/*GetDockerRegistriesOK handles this case with default header values.

Success
*/
type GetDockerRegistriesOK struct {
	Payload []*models.DockerRegistryAuthDto
}

func (o *GetDockerRegistriesOK) Error() string {
	return fmt.Sprintf("[GET /api/admin/docker/registry][%d] getDockerRegistriesOK  %+v", 200, o.Payload)
}

func (o *GetDockerRegistriesOK) GetPayload() []*models.DockerRegistryAuthDto {
	return o.Payload
}

func (o *GetDockerRegistriesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDockerRegistriesUnauthorized creates a GetDockerRegistriesUnauthorized with default headers values
func NewGetDockerRegistriesUnauthorized() *GetDockerRegistriesUnauthorized {
	return &GetDockerRegistriesUnauthorized{}
}

/*GetDockerRegistriesUnauthorized handles this case with default header values.

Unauthorized
*/
type GetDockerRegistriesUnauthorized struct {
}

func (o *GetDockerRegistriesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/admin/docker/registry][%d] getDockerRegistriesUnauthorized ", 401)
}

func (o *GetDockerRegistriesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDockerRegistriesForbidden creates a GetDockerRegistriesForbidden with default headers values
func NewGetDockerRegistriesForbidden() *GetDockerRegistriesForbidden {
	return &GetDockerRegistriesForbidden{}
}

/*GetDockerRegistriesForbidden handles this case with default header values.

Forbidden
*/
type GetDockerRegistriesForbidden struct {
}

func (o *GetDockerRegistriesForbidden) Error() string {
	return fmt.Sprintf("[GET /api/admin/docker/registry][%d] getDockerRegistriesForbidden ", 403)
}

func (o *GetDockerRegistriesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
