// Code generated by go-swagger; DO NOT EDIT.

package admin_setting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCurrentParams creates a new GetCurrentParams object
// with the default values initialized.
func NewGetCurrentParams() *GetCurrentParams {

	return &GetCurrentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCurrentParamsWithTimeout creates a new GetCurrentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCurrentParamsWithTimeout(timeout time.Duration) *GetCurrentParams {

	return &GetCurrentParams{

		timeout: timeout,
	}
}

// NewGetCurrentParamsWithContext creates a new GetCurrentParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCurrentParamsWithContext(ctx context.Context) *GetCurrentParams {

	return &GetCurrentParams{

		Context: ctx,
	}
}

// NewGetCurrentParamsWithHTTPClient creates a new GetCurrentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCurrentParamsWithHTTPClient(client *http.Client) *GetCurrentParams {

	return &GetCurrentParams{
		HTTPClient: client,
	}
}

/*GetCurrentParams contains all the parameters to send to the API endpoint
for the get current operation typically these are written to a http.Request
*/
type GetCurrentParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get current params
func (o *GetCurrentParams) WithTimeout(timeout time.Duration) *GetCurrentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get current params
func (o *GetCurrentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get current params
func (o *GetCurrentParams) WithContext(ctx context.Context) *GetCurrentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get current params
func (o *GetCurrentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get current params
func (o *GetCurrentParams) WithHTTPClient(client *http.Client) *GetCurrentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get current params
func (o *GetCurrentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCurrentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
