// Code generated by go-swagger; DO NOT EDIT.

package admin_setting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"cli/models"
)

// NewSetCurrentParams creates a new SetCurrentParams object
// with the default values initialized.
func NewSetCurrentParams() *SetCurrentParams {
	var ()
	return &SetCurrentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetCurrentParamsWithTimeout creates a new SetCurrentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetCurrentParamsWithTimeout(timeout time.Duration) *SetCurrentParams {
	var ()
	return &SetCurrentParams{

		timeout: timeout,
	}
}

// NewSetCurrentParamsWithContext creates a new SetCurrentParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetCurrentParamsWithContext(ctx context.Context) *SetCurrentParams {
	var ()
	return &SetCurrentParams{

		Context: ctx,
	}
}

// NewSetCurrentParamsWithHTTPClient creates a new SetCurrentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetCurrentParamsWithHTTPClient(client *http.Client) *SetCurrentParams {
	var ()
	return &SetCurrentParams{
		HTTPClient: client,
	}
}

/*SetCurrentParams contains all the parameters to send to the API endpoint
for the set current operation typically these are written to a http.Request
*/
type SetCurrentParams struct {

	/*Settings*/
	Settings *models.ServiceParametersModelDto

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set current params
func (o *SetCurrentParams) WithTimeout(timeout time.Duration) *SetCurrentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set current params
func (o *SetCurrentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set current params
func (o *SetCurrentParams) WithContext(ctx context.Context) *SetCurrentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set current params
func (o *SetCurrentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set current params
func (o *SetCurrentParams) WithHTTPClient(client *http.Client) *SetCurrentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set current params
func (o *SetCurrentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSettings adds the settings to the set current params
func (o *SetCurrentParams) WithSettings(settings *models.ServiceParametersModelDto) *SetCurrentParams {
	o.SetSettings(settings)
	return o
}

// SetSettings adds the settings to the set current params
func (o *SetCurrentParams) SetSettings(settings *models.ServiceParametersModelDto) {
	o.Settings = settings
}

// WriteToRequest writes these params to a swagger request
func (o *SetCurrentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Settings != nil {
		if err := r.SetBodyParam(o.Settings); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
