// Code generated by go-swagger; DO NOT EDIT.

package admin_setting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"cli/models"
)

// NewUpdateDockerRegistryParams creates a new UpdateDockerRegistryParams object
// with the default values initialized.
func NewUpdateDockerRegistryParams() *UpdateDockerRegistryParams {
	var ()
	return &UpdateDockerRegistryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateDockerRegistryParamsWithTimeout creates a new UpdateDockerRegistryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateDockerRegistryParamsWithTimeout(timeout time.Duration) *UpdateDockerRegistryParams {
	var ()
	return &UpdateDockerRegistryParams{

		timeout: timeout,
	}
}

// NewUpdateDockerRegistryParamsWithContext creates a new UpdateDockerRegistryParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateDockerRegistryParamsWithContext(ctx context.Context) *UpdateDockerRegistryParams {
	var ()
	return &UpdateDockerRegistryParams{

		Context: ctx,
	}
}

// NewUpdateDockerRegistryParamsWithHTTPClient creates a new UpdateDockerRegistryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateDockerRegistryParamsWithHTTPClient(client *http.Client) *UpdateDockerRegistryParams {
	var ()
	return &UpdateDockerRegistryParams{
		HTTPClient: client,
	}
}

/*UpdateDockerRegistryParams contains all the parameters to send to the API endpoint
for the update docker registry operation typically these are written to a http.Request
*/
type UpdateDockerRegistryParams struct {

	/*Data*/
	Data *models.DockerRegistryAuthDto

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update docker registry params
func (o *UpdateDockerRegistryParams) WithTimeout(timeout time.Duration) *UpdateDockerRegistryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update docker registry params
func (o *UpdateDockerRegistryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update docker registry params
func (o *UpdateDockerRegistryParams) WithContext(ctx context.Context) *UpdateDockerRegistryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update docker registry params
func (o *UpdateDockerRegistryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update docker registry params
func (o *UpdateDockerRegistryParams) WithHTTPClient(client *http.Client) *UpdateDockerRegistryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update docker registry params
func (o *UpdateDockerRegistryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the update docker registry params
func (o *UpdateDockerRegistryParams) WithData(data *models.DockerRegistryAuthDto) *UpdateDockerRegistryParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the update docker registry params
func (o *UpdateDockerRegistryParams) SetData(data *models.DockerRegistryAuthDto) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateDockerRegistryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
