// Code generated by go-swagger; DO NOT EDIT.

package admin_setting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateKubeClusterReader is a Reader for the UpdateKubeCluster structure.
type UpdateKubeClusterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateKubeClusterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateKubeClusterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewUpdateKubeClusterUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateKubeClusterForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateKubeClusterOK creates a UpdateKubeClusterOK with default headers values
func NewUpdateKubeClusterOK() *UpdateKubeClusterOK {
	return &UpdateKubeClusterOK{}
}

/*UpdateKubeClusterOK handles this case with default header values.

Success
*/
type UpdateKubeClusterOK struct {
}

func (o *UpdateKubeClusterOK) Error() string {
	return fmt.Sprintf("[PATCH /api/admin/clusters/k8s][%d] updateKubeClusterOK ", 200)
}

func (o *UpdateKubeClusterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateKubeClusterUnauthorized creates a UpdateKubeClusterUnauthorized with default headers values
func NewUpdateKubeClusterUnauthorized() *UpdateKubeClusterUnauthorized {
	return &UpdateKubeClusterUnauthorized{}
}

/*UpdateKubeClusterUnauthorized handles this case with default header values.

Unauthorized
*/
type UpdateKubeClusterUnauthorized struct {
}

func (o *UpdateKubeClusterUnauthorized) Error() string {
	return fmt.Sprintf("[PATCH /api/admin/clusters/k8s][%d] updateKubeClusterUnauthorized ", 401)
}

func (o *UpdateKubeClusterUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateKubeClusterForbidden creates a UpdateKubeClusterForbidden with default headers values
func NewUpdateKubeClusterForbidden() *UpdateKubeClusterForbidden {
	return &UpdateKubeClusterForbidden{}
}

/*UpdateKubeClusterForbidden handles this case with default header values.

Forbidden
*/
type UpdateKubeClusterForbidden struct {
}

func (o *UpdateKubeClusterForbidden) Error() string {
	return fmt.Sprintf("[PATCH /api/admin/clusters/k8s][%d] updateKubeClusterForbidden ", 403)
}

func (o *UpdateKubeClusterForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
