// Code generated by go-swagger; DO NOT EDIT.

package archive_analysis

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewAnalyseParams creates a new AnalyseParams object
// with the default values initialized.
func NewAnalyseParams() *AnalyseParams {
	var ()
	return &AnalyseParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAnalyseParamsWithTimeout creates a new AnalyseParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAnalyseParamsWithTimeout(timeout time.Duration) *AnalyseParams {
	var ()
	return &AnalyseParams{

		timeout: timeout,
	}
}

// NewAnalyseParamsWithContext creates a new AnalyseParams object
// with the default values initialized, and the ability to set a context for a request
func NewAnalyseParamsWithContext(ctx context.Context) *AnalyseParams {
	var ()
	return &AnalyseParams{

		Context: ctx,
	}
}

// NewAnalyseParamsWithHTTPClient creates a new AnalyseParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAnalyseParamsWithHTTPClient(client *http.Client) *AnalyseParams {
	var ()
	return &AnalyseParams{
		HTTPClient: client,
	}
}

/*AnalyseParams contains all the parameters to send to the API endpoint
for the analyse operation typically these are written to a http.Request
*/
type AnalyseParams struct {

	/*FileID*/
	FileID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the analyse params
func (o *AnalyseParams) WithTimeout(timeout time.Duration) *AnalyseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the analyse params
func (o *AnalyseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the analyse params
func (o *AnalyseParams) WithContext(ctx context.Context) *AnalyseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the analyse params
func (o *AnalyseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the analyse params
func (o *AnalyseParams) WithHTTPClient(client *http.Client) *AnalyseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the analyse params
func (o *AnalyseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFileID adds the fileID to the analyse params
func (o *AnalyseParams) WithFileID(fileID int32) *AnalyseParams {
	o.SetFileID(fileID)
	return o
}

// SetFileID adds the fileId to the analyse params
func (o *AnalyseParams) SetFileID(fileID int32) {
	o.FileID = fileID
}

// WriteToRequest writes these params to a swagger request
func (o *AnalyseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param fileId
	if err := r.SetPathParam("fileId", swag.FormatInt32(o.FileID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
