// Code generated by go-swagger; DO NOT EDIT.

package archive_analysis

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new archive analysis API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for archive analysis API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	Analyse(params *AnalyseParams, authInfo runtime.ClientAuthInfoWriter) (*AnalyseOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  Analyse analyse API
*/
func (a *Client) Analyse(params *AnalyseParams, authInfo runtime.ClientAuthInfoWriter) (*AnalyseOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAnalyseParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Analyse",
		Method:             "GET",
		PathPattern:        "/api/archive-analysis/{fileId}",
		ProducesMediaTypes: []string{"application/json", "text/json", "text/plain"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &AnalyseReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AnalyseOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Analyse: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
