// Code generated by go-swagger; DO NOT EDIT.

package docker

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"cli/models"
)

// NewCheckRegistryParams creates a new CheckRegistryParams object
// with the default values initialized.
func NewCheckRegistryParams() *CheckRegistryParams {
	var ()
	return &CheckRegistryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCheckRegistryParamsWithTimeout creates a new CheckRegistryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCheckRegistryParamsWithTimeout(timeout time.Duration) *CheckRegistryParams {
	var ()
	return &CheckRegistryParams{

		timeout: timeout,
	}
}

// NewCheckRegistryParamsWithContext creates a new CheckRegistryParams object
// with the default values initialized, and the ability to set a context for a request
func NewCheckRegistryParamsWithContext(ctx context.Context) *CheckRegistryParams {
	var ()
	return &CheckRegistryParams{

		Context: ctx,
	}
}

// NewCheckRegistryParamsWithHTTPClient creates a new CheckRegistryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCheckRegistryParamsWithHTTPClient(client *http.Client) *CheckRegistryParams {
	var ()
	return &CheckRegistryParams{
		HTTPClient: client,
	}
}

/*CheckRegistryParams contains all the parameters to send to the API endpoint
for the check registry operation typically these are written to a http.Request
*/
type CheckRegistryParams struct {

	/*Data*/
	Data *models.PrivateImageDto

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the check registry params
func (o *CheckRegistryParams) WithTimeout(timeout time.Duration) *CheckRegistryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the check registry params
func (o *CheckRegistryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the check registry params
func (o *CheckRegistryParams) WithContext(ctx context.Context) *CheckRegistryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the check registry params
func (o *CheckRegistryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the check registry params
func (o *CheckRegistryParams) WithHTTPClient(client *http.Client) *CheckRegistryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the check registry params
func (o *CheckRegistryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the check registry params
func (o *CheckRegistryParams) WithData(data *models.PrivateImageDto) *CheckRegistryParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the check registry params
func (o *CheckRegistryParams) SetData(data *models.PrivateImageDto) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *CheckRegistryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
