// Code generated by go-swagger; DO NOT EDIT.

package ready_application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cli/models"
)

// DeployReader is a Reader for the Deploy structure.
type DeployReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeployReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeployOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeployUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeployForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeployOK creates a DeployOK with default headers values
func NewDeployOK() *DeployOK {
	return &DeployOK{}
}

/*DeployOK handles this case with default header values.

Success
*/
type DeployOK struct {
	Payload *models.ApplicationSummaryDto
}

func (o *DeployOK) Error() string {
	return fmt.Sprintf("[POST /api/ready-applications/{id}/deploy][%d] deployOK  %+v", 200, o.Payload)
}

func (o *DeployOK) GetPayload() *models.ApplicationSummaryDto {
	return o.Payload
}

func (o *DeployOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApplicationSummaryDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeployUnauthorized creates a DeployUnauthorized with default headers values
func NewDeployUnauthorized() *DeployUnauthorized {
	return &DeployUnauthorized{}
}

/*DeployUnauthorized handles this case with default header values.

Unauthorized
*/
type DeployUnauthorized struct {
}

func (o *DeployUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/ready-applications/{id}/deploy][%d] deployUnauthorized ", 401)
}

func (o *DeployUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeployForbidden creates a DeployForbidden with default headers values
func NewDeployForbidden() *DeployForbidden {
	return &DeployForbidden{}
}

/*DeployForbidden handles this case with default header values.

Forbidden
*/
type DeployForbidden struct {
}

func (o *DeployForbidden) Error() string {
	return fmt.Sprintf("[POST /api/ready-applications/{id}/deploy][%d] deployForbidden ", 403)
}

func (o *DeployForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
