name: Release

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    
    - name: Set Version
      run: echo "::set-env name=VERSION::$(./git-semver.sh)"

    - name: Build
      run: ./build-bin.sh

    - name: Create a Release
      uses: actions/create-release@v1.1.1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag
        tag_name: ${{ env.VERSION }}
        # The name of the release. For example, `Release v1.0.1`
        release_name: Release ${{ env.VERSION }}
        # `true` to create a draft (unpublished) release, `false` to create a published one. Default: `false`
        draft: false
