// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AdminStatsDto admin stats dto
//
// swagger:model AdminStatsDto
type AdminStatsDto struct {

	// all apps count
	// Read Only: true
	AllAppsCount int32 `json:"allAppsCount,omitempty"`

	// all user count
	// Read Only: true
	AllUserCount int32 `json:"allUserCount,omitempty"`

	// last month user count
	// Read Only: true
	LastMonthUserCount int32 `json:"lastMonthUserCount,omitempty"`

	// last week user count
	// Read Only: true
	LastWeekUserCount int32 `json:"lastWeekUserCount,omitempty"`

	// requested Cpu
	// Read Only: true
	RequestedCPU float32 `json:"requestedCpu,omitempty"`

	// requested disk
	// Read Only: true
	RequestedDisk float32 `json:"requestedDisk,omitempty"`

	// requested Ip
	// Read Only: true
	RequestedIP int32 `json:"requestedIp,omitempty"`

	// requested Ram
	// Read Only: true
	RequestedRAM float32 `json:"requestedRam,omitempty"`

	// started apps count
	// Read Only: true
	StartedAppsCount int32 `json:"startedAppsCount,omitempty"`

	// yesterday user count
	// Read Only: true
	YesterdayUserCount int32 `json:"yesterdayUserCount,omitempty"`
}

// Validate validates this admin stats dto
func (m *AdminStatsDto) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AdminStatsDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AdminStatsDto) UnmarshalBinary(b []byte) error {
	var res AdminStatsDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
