// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ApplicationStatusDto application status dto
//
// swagger:model ApplicationStatusDto
type ApplicationStatusDto struct {

	// app Id
	AppID int32 `json:"appId,omitempty"`

	// error instances
	ErrorInstances int32 `json:"errorInstances,omitempty"`

	// is started
	IsStarted bool `json:"isStarted,omitempty"`

	// penging instances
	PengingInstances int32 `json:"pengingInstances,omitempty"`

	// running instances
	RunningInstances int32 `json:"runningInstances,omitempty"`
}

// Validate validates this application status dto
func (m *ApplicationStatusDto) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ApplicationStatusDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApplicationStatusDto) UnmarshalBinary(b []byte) error {
	var res ApplicationStatusDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
