// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ApplicationEndpointDto application endpoint dto
//
// swagger:model ApplicationEndpointDto
type ApplicationEndpointDto struct {

	// app Id
	AppID int32 `json:"appId,omitempty"`

	// endpoints
	Endpoints []string `json:"endpoints"`

	// is fully exposed
	IsFullyExposed bool `json:"isFullyExposed,omitempty"`
}

// Validate validates this application endpoint dto
func (m *ApplicationEndpointDto) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ApplicationEndpointDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApplicationEndpointDto) UnmarshalBinary(b []byte) error {
	var res ApplicationEndpointDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
