// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ApplicationConfigFileDto application config file dto
//
// swagger:model ApplicationConfigFileDto
type ApplicationConfigFileDto struct {

	// file Id
	FileID int32 `json:"fileId,omitempty"`

	// id
	ID int32 `json:"id,omitempty"`

	// is binary
	IsBinary bool `json:"isBinary,omitempty"`

	// path
	Path string `json:"path,omitempty"`
}

// Validate validates this application config file dto
func (m *ApplicationConfigFileDto) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ApplicationConfigFileDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApplicationConfigFileDto) UnmarshalBinary(b []byte) error {
	var res ApplicationConfigFileDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
