// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ArchiveAnalysisVariantDto archive analysis variant dto
//
// swagger:model ArchiveAnalysisVariantDto
type ArchiveAnalysisVariantDto struct {

	// commands list
	CommandsList []string `json:"commandsList"`

	// docker image
	DockerImage string `json:"dockerImage,omitempty"`

	// priority
	Priority int32 `json:"priority,omitempty"`

	// run comand
	RunComand string `json:"runComand,omitempty"`

	// trigger files
	TriggerFiles []string `json:"triggerFiles"`

	// variant name
	VariantName string `json:"variantName,omitempty"`

	// working dir
	WorkingDir string `json:"workingDir,omitempty"`
}

// Validate validates this archive analysis variant dto
func (m *ArchiveAnalysisVariantDto) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ArchiveAnalysisVariantDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ArchiveAnalysisVariantDto) UnmarshalBinary(b []byte) error {
	var res ArchiveAnalysisVariantDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
