// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DockerFileTextDto docker file text dto
//
// swagger:model DockerFileTextDto
type DockerFileTextDto struct {

	// body
	Body string `json:"body,omitempty"`
}

// Validate validates this docker file text dto
func (m *DockerFileTextDto) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DockerFileTextDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DockerFileTextDto) UnmarshalBinary(b []byte) error {
	var res DockerFileTextDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
