// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PageDtoBillingAuditEventDto page dto billing audit event dto
//
// swagger:model PageDto[BillingAuditEventDto]
type PageDtoBillingAuditEventDto struct {

	// count
	Count int32 `json:"count,omitempty"`

	// items
	Items []*BillingAuditEventDto `json:"items"`

	// items per page
	ItemsPerPage int32 `json:"itemsPerPage,omitempty"`

	// page
	Page int32 `json:"page,omitempty"`
}

// Validate validates this page dto billing audit event dto
func (m *PageDtoBillingAuditEventDto) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateItems(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PageDtoBillingAuditEventDto) validateItems(formats strfmt.Registry) error {

	if swag.IsZero(m.Items) { // not required
		return nil
	}

	for i := 0; i < len(m.Items); i++ {
		if swag.IsZero(m.Items[i]) { // not required
			continue
		}

		if m.Items[i] != nil {
			if err := m.Items[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("items" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PageDtoBillingAuditEventDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PageDtoBillingAuditEventDto) UnmarshalBinary(b []byte) error {
	var res PageDtoBillingAuditEventDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
