// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServiceParametersModelDto service parameters model dto
//
// swagger:model ServiceParametersModelDto
type ServiceParametersModelDto struct {

	// application amount per day
	ApplicationAmountPerDay int32 `json:"applicationAmountPerDay,omitempty"`

	// bill period
	BillPeriod string `json:"billPeriod,omitempty"`

	// can users create new applications
	CanUsersCreateNewApplications bool `json:"canUsersCreateNewApplications,omitempty"`

	// default plan
	DefaultPlan string `json:"defaultPlan,omitempty"`

	// id
	ID int32 `json:"id,omitempty"`

	// is enabled
	IsEnabled bool `json:"isEnabled,omitempty"`

	// user start balance
	UserStartBalance int32 `json:"userStartBalance,omitempty"`
}

// Validate validates this service parameters model dto
func (m *ServiceParametersModelDto) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceParametersModelDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceParametersModelDto) UnmarshalBinary(b []byte) error {
	var res ServiceParametersModelDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
